# -*- coding: utf-8 -*-
{
    'name': "hr_candidato",
    'summary': "",
    'description': """
     This functionality goes through several stages during its execution, since the candidate must go through each of the stages of the selection process, such as: preliminary interview, knowledge interview, verification of psychological aptitudes, verification of physical attitudes, verifications socio-labour, analysis in committee of experts, analysis in board of directors and results report.
    """,
    'author': "Glezvidal",
    'website': "http://www.yourcompany.com",
    'category': 'Proceso de Selección',
    'version': '0.1',
    'depends': ['base',
                'hr_recruitment',
                'website_slides',
                'report_xlsx'
                ],
    'data': [
        'security/hr_segurity_recruitment.xml',
        'security/segurity_hr_nomengladores.xml',
        'security/segurity_hr_modelo.xml',
        'security/ir.model.access.csv',
        'report/hr_mouth_doc.xml',
        'report/hr_job_xlsx.xml',
        'report/hr_stage_pdf.xml',
        'report/hr_course_pdf.xml',
        'report/hr_year_pdf.xml',
        'wizard/hr_w_mouth_report.xml',
        'wizard/hr_w_stage_report.xml',
        'wizard/hr_w_course_report.xml',
        'wizard/hr_w_year_report.xml',
        'wizard/hr_w_job_report.xml',
        'views/hr_recruitment_views.xml',
        'views/hr_area_views.xml',
        'views/hr_search_Re_views.xml',
        'views/hr_abstract_views.xml',
        'views/hr_pre-employment_views.xml',
        'views/hr_evaluate_views.xml',
        'views/res_company_views.xml',
        'views/hr_ueb_views.xml',
        'views/hr_n_area_views.xml',
        'views/hr_job_views.xml',
        'views/hr_slide_views.xml',
        'views/hr_aspect_views.xml',
        'views/hr_stage_views.xml',
        'views/hr_psychological_views.xml',
        'views/templates.xml',
        'views/hr_menu.xml',
    ],
    'application': True,
    'installable': True,
}
